name: "Apply"
description: "Applies a Terraform deployment"
inputs:
  aws_account_id:
    description: "The ID of the AWS account to operate on"
    required: true
  environment:
    description: "The name of the development environment to run plan against"
    required: true
  aws_region:
    description: "The AWS region being used"
    required: false
    default: "us-east-1"
  terraform_version:
    description: "The version of Terraform to use"
    required: false
    default: "1.3.2"

outputs:
  apply_outcome:
    description: "The outcome of the Terraform apply step"
    value: ${{ steps.apply.outcome }}
  apply_output:
    description: "The output of the Terraform apply step"
    value: ${{ steps.apply.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/cache@v3
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/terraform
        role-session-name: ${{ github.triggering_actor }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform Apply
      shell: bash
      run: terraform apply -auto-approve -input=false "plan.tfplan"
