name: "Terraform"
on:
  push:
    branches-ignore:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jasonjanderson/terraform-actions
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: .github/workflows/terraform-actions
          ref: main

      - uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

  staging:
    needs: setup
    uses: ./github/workflows/terraform-actions/terraform.yml
    with:
      environment: staging
      aws_account_id: "889550907551"
      plan_only: false

  production:
    needs: setup
    uses: ./github/workflows/terraform-actions/terraform.yml
    with:
      environment: production
      aws_account_id: "889550907551"
