name: "Terraform"
on:
  push:
    branches-ignore:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: jasonjanderson/terraform-actions
          token: ${{ secrets.GH_PAT }}
          path: terraform-actions
          #ref: main

      - name: ls
        run: ls -alh
      - name: ls again
        run: ls -alh . && ls -alh .github/workflows
      - uses: ./terraform-actions/terraform-plan
        with:
          # environment: staging
          aws_account_id: "889550907551"
          # plan_only: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # staging:
  #   needs: setup
  #   uses: ./.github/workflows/terraform.yml
  #   with:
  #     environment: staging
  #     aws_account_id: "889550907551"
  #     plan_only: false

  # production:
  #   needs: setup
  #   uses: ./.github/workflows/terraform.yml
  #   with:
  #     environment: production
  #     aws_account_id: "889550907551"
