name: "Plan"
on:
  push:
    branches-ignore:
      - main
jobs:
  staging:
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: staging
      aws_account_id: "889550907551"
  production:
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: production
      aws_account_id: "889550907551"
